- banner:
  - link "Siemens logo":
    - /url: "#/"
  - text: My application
  - navigation "Main navigation":
    - link "Module 1":
      - /url: "#/viewer/viewer/m1"
    - button "Module 2"
  - button "Tenant 2"
  - button "Notifications"
  - button /\+\d+ Support/
  - button "Settings"
  - button "Lars Vegas"